### PR TITLE
Merge richmahn/tools into unfoldingWord-dev/tools

### PR DESCRIPTION
**Pull request by richmahn**
* Added many scripts in uwb for exporting tN, tW, tQ, tA vol1 and vol2, ulb and udb
* Modified general_tools/pandoc_pdf_template.txt

### CODE REVIEW

**Comment by jag3773** [comment]
@richmahn There are binary font files in here that I don't think we want.

**Comment by richmahn** [comment]
@jag3773 Yeah, was just looking at that...don't need those, currently removing them.

**Comment by richmahn** [comment]
Had put those there for Ken to put into the system.

**Comment by richmahn** [comment]
Removed.

**Comment by jag3773** [comment]
The noto fonts are in /usr/share/fonts/google-noto/ on the system, btw.

**Pull request merged**
