### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jag3773**
Merge dev into master to get all of @alerque 's PDF changes.

### CODE REVIEW

**Comment by alerque** [comment]
Umm...can we perhaps deploy the development branch to the test server and bash on it a bit there first and reserve merges to master for production releases? I'm not quite comfortable with this having not gotten tested yet (or am I missing that? How did it work on systems other than mine?). Also for production it might be worth waiting a couple days for scrips that will be easier to wire up to the production api...

**Comment by phillip-hopper** [comment]
@alerque The development branch is staged on test.door43.org.

**Comment by alerque** [comment]
@phillip-hopper huh. All I have access to is the test server which looks like its still in the branch where I did the initial stages of collecting this work. So is there a staging site separate from production? And this couldn't have been there very long as it was only merged to develop just before this PR. How did the ConTeXt (re)install/cleanup go? Did this work to get the environment going and the font cache primed? In the rush to get this submitted before being on the road I never tested outside of Arch Linux...

**Comment by phillip-hopper** [comment]
@alerque I can't help you with that, sorry.

**Comment by alerque** [comment]
@phillip-hopper PR #91 should really have been merged into develop before develop was merged into master. This change set is kind of half baked and I did a lot of work after this to clean things up. Cat you look at merging that one and then doing another develop->master merge? I'd hate to see time wasted adapting to this script usage in production without the other fixes as well.

**Pull request merged**
